export const BRAZILIAN_BANKS = [
  { code: "001", name: "Banco do Brasil" },
  { code: "003", name: "Banco da Amazônia" },
  { code: "004", name: "Banco do Nordeste" },
  { code: "021", name: "Banestes" },
  { code: "033", name: "Santander" },
  { code: "041", name: "Banrisul" },
  { code: "070", name: "BRB" },
  { code: "077", name: "Banco Inter" },
  { code: "104", name: "Caixa Econômica Federal" },
  { code: "121", name: "Agibank" },
  { code: "136", name: "Unicred" },
  { code: "169", name: "Banco Olé" },
  { code: "197", name: "Stone" },
  { code: "208", bame: "BTG Pactual" },
  { code: "212", name: "Banco Original" },
  { code: "218", name: "Banco BS2 / Bonsucesso" },
  { code: "237", name: "Bradesco" },
  { code: "246", name: "Banco ABC Brasil" },
  { code: "260", name: "Nubank" },
  { code: "290", name: "PagSeguro" },
  { code: "318", name: "Banco BMG" },
  { code: "323", name: "Mercado Pago" },
  { code: "330", name: "Banco Bari" },
  { code: "336", name: "Banco C6" },
  { code: "341", name: "Itaú Unibanco" },
  { code: "348", name: "Banco XP" },
  { code: "356", name: "Banco Real (legado)" },
  { code: "380", name: "PicPay Bank" },
  { code: "389", name: "Banco Mercantil" },
  { code: "422", name: "Banco Safra" },
  { code: "623", name: "Banco Pan" },
  { code: "633", name: "Rendimento" },
  { code: "655", name: "Votorantim" },
  { code: "707", name: "Daycoval" },
  { code: "735", name: "Neon / Banco Digio" },
  { code: "739", name: "Cetelem (legado)" },
  { code: "748", name: "Sicredi" },
  { code: "756", name: "Sicoob" },
];

export const INTERNATIONAL_BANKS = [
  { code: "JPM", name: "JPMorgan Chase" },
  { code: "BOA", name: "Bank of America" },
  { code: "CITI", name: "Citibank" },
  { code: "WF", name: "Wells Fargo" },
  { code: "GS", name: "Goldman Sachs" },
  { code: "MS", name: "Morgan Stanley" },
  { code: "HSBC", name: "HSBC" },
  { code: "BARC", name: "Barclays" },
  { code: "SC", name: "Standard Chartered" },
  { code: "LLOY", name: "Lloyds Bank" },
  { code: "DB", name: "Deutsche Bank" },
  { code: "COMM", name: "Commerzbank" },
  { code: "BNP", name: "BNP Paribas" },
  { code: "CA", name: "Crédit Agricole" },
  { code: "SG", name: "Société Générale" },
  { code: "UBS", name: "UBS" },
  { code: "CS", name: "Credit Suisse" },
  { code: "ING", name: "ING Bank" },
  { code: "RABO", name: "Rabobank" },
  { code: "SANT_G", name: "Santander Global" },
  { code: "BBVA", name: "BBVA" },
  { code: "CXBK", name: "CaixaBank" },
  { code: "UNI", name: "UniCredit" },
  { code: "INT", name: "Intesa Sanpaolo" },
  { code: "CG", name: "Banco do Estado Português / Caixa Geral" },
  { code: "ICBC", name: "ICBC" },
  { code: "BOC", name: "Bank of China" },
  { code: "CCB", bame: "China Construction Bank" },
  { code: "ABC", name: "Agricultural Bank of China" },
  { code: "MZ", name: "Mizuho Bank" },
  { code: "MUFG", name: "MUFG Bank" },
  { code: "SM", name: "Sumitomo Mitsui" },
  { code: "DBS", name: "DBS Bank" },
  { code: "OCBC", name: "OCBC Bank" },
  { code: "UOB", name: "UOB" },
  { code: "ENBD", name: "Emirates NBD" },
  { code: "FAB", name: "First Abu Dhabi Bank" },
  { code: "QNB", name: "QNB" },
  { code: "RBC", name: "Royal Bank of Canada" },
  { code: "TD", name: "TD Bank" },
  { code: "SB", name: "Scotiabank" },
  { code: "BMO", name: "BMO" },
  { code: "NBC", name: "National Bank of Canada" },
];

export const ALL_BANKS = [
  ...BRAZILIAN_BANKS.map(b => ({ ...b, category: 'Brasileiro' })),
  ...INTERNATIONAL_BANKS.map(b => ({ ...b, category: 'Internacional' })),
];
