-- MIGRATION: V39 - ADD SPEED AND HEADING COLUMNS FOR DELIVERY TRACKING
BEGIN;

ALTER TABLE public.delivery_tracking 
ADD COLUMN IF NOT EXISTS speed NUMERIC,
ADD COLUMN IF NOT EXISTS heading NUMERIC,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

COMMIT;

-- Force PostgREST schema cache reload
NOTIFY pgrst, 'reload schema';
